In [36]:
import numpy as np

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
array_monodimensional = np.array([1,2,5,7,8])

In [7]:
array_monodimensional

array([1, 2, 5, 7, 8])

In [8]:
type(array_monodimensional)

numpy.ndarray

In [9]:
array_bidimensional = np.array([[1,2,5,7,8], [3,4,5,9,0], [2,5,7,9,1]])

In [10]:
array_bidimensional

array([[1, 2, 5, 7, 8],
       [3, 4, 5, 9, 0],
       [2, 5, 7, 9, 1]])

In [11]:
matrice_suma = array_bidimensional + array_bidimensional
matrice_suma

array([[ 2,  4, 10, 14, 16],
       [ 6,  8, 10, 18,  0],
       [ 4, 10, 14, 18,  2]])

In [13]:
matrice_inmultita = array_bidimensional * array_bidimensional
matrice_inmultita

array([[ 1,  4, 25, 49, 64],
       [ 9, 16, 25, 81,  0],
       [ 4, 25, 49, 81,  1]])

In [17]:
matrice = np.random.random((3,5))
matrice

array([[0.23188246, 0.67579982, 0.67094027, 0.00921058, 0.45792346],
       [0.834183  , 0.59191188, 0.5955805 , 0.10451115, 0.39725814],
       [0.84545438, 0.52984644, 0.07555806, 0.76230706, 0.26765604]])

In [25]:
np.random.seed(42)
matrice_multidimensionala=np.random.random((3,3,3,5))
matrice_multidimensionala

array([[[[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
         [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
         [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497]],

        [[0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
         [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998],
         [0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041]],

        [[0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203],
         [0.80839735, 0.30461377, 0.09767211, 0.68423303, 0.44015249],
         [0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998]]],


       [[[0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446],
         [0.96958463, 0.77513282, 0.93949894, 0.89482735, 0.59789998],
         [0.92187424, 0.0884925 , 0.19598286, 0.04522729, 0.32533033]],

        [[0.38867729, 0.27134903, 0.82873751, 0.35675333, 0.28093451],
         [0.54269608, 0.14092422, 0.80219698, 0.07455064, 0.9868869

In [26]:
matrice_multidimensionala=np.random.random((3,3,3,5))
matrice_multidimensionala

array([[[[0.32320293, 0.51879062, 0.70301896, 0.3636296 , 0.97178208],
         [0.96244729, 0.2517823 , 0.49724851, 0.30087831, 0.28484049],
         [0.03688695, 0.60956433, 0.50267902, 0.05147875, 0.27864646]],

        [[0.90826589, 0.23956189, 0.14489487, 0.48945276, 0.98565045],
         [0.24205527, 0.67213555, 0.76161962, 0.23763754, 0.72821635],
         [0.36778313, 0.63230583, 0.63352971, 0.53577468, 0.09028977]],

        [[0.8353025 , 0.32078006, 0.18651851, 0.04077514, 0.59089294],
         [0.67756436, 0.01658783, 0.51209306, 0.22649578, 0.64517279],
         [0.17436643, 0.69093774, 0.38673535, 0.93672999, 0.13752094]]],


       [[[0.34106635, 0.11347352, 0.92469362, 0.87733935, 0.25794163],
         [0.65998405, 0.8172222 , 0.55520081, 0.52965058, 0.24185229],
         [0.09310277, 0.89721576, 0.90041806, 0.63310146, 0.33902979]],

        [[0.34920957, 0.72595568, 0.89711026, 0.88708642, 0.77987555],
         [0.64203165, 0.08413996, 0.16162871, 0.89855419, 0.6064290

In [35]:
matrice_multidimensionala=nrd.random((3,3,3,5))
matrice_multidimensionala

array([[[[0.67202614, 0.32815267, 0.15504162, 0.98184089, 0.8389335 ],
         [0.86040462, 0.25025136, 0.03883473, 0.30326551, 0.53708243],
         [0.32665124, 0.827869  , 0.27154292, 0.96525183, 0.45726516]],

        [[0.84202308, 0.19438003, 0.41135391, 0.69951221, 0.13835309],
         [0.13274542, 0.96953687, 0.7145951 , 0.04106752, 0.3988209 ],
         [0.43352074, 0.74404264, 0.25086053, 0.18433367, 0.08087297]],

        [[0.42831447, 0.6884999 , 0.0581936 , 0.91521373, 0.44235223],
         [0.23978736, 0.09387329, 0.182866  , 0.934614  , 0.63827059],
         [0.51669626, 0.65711133, 0.4356729 , 0.73003932, 0.04771613]]],


       [[[0.56603721, 0.15864645, 0.12016465, 0.34187967, 0.09179907],
         [0.09415699, 0.31141331, 0.97951053, 0.17533027, 0.0171611 ],
         [0.76336442, 0.80691298, 0.34630432, 0.46467381, 0.64977368]],

        [[0.04805892, 0.94914573, 0.88668039, 0.26089362, 0.01530454],
         [0.93343631, 0.50103988, 0.53937745, 0.68396377, 0.6158511

In [27]:
matrice_nr_intregi = np.random.randint(100,1000, (5,5))
matrice_nr_intregi

array([[858, 637, 966, 917, 507],
       [624, 927, 605, 924, 135],
       [784, 119, 420, 875, 611],
       [499, 753, 982, 570, 242],
       [191, 453, 933, 899, 826]])

In [41]:
matrice_zerouri = np.zeros((5,5), dtype="float16")
matrice_zerouri

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)

In [42]:
type(matrice_zerouri[0, 0])

numpy.float16

In [43]:
matrice_zerouri = np.zeros((5,5), dtype="int8")
matrice_zerouri

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [44]:
matrice_unu = np.ones((5,5), dtype="int8")
matrice_unu

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [ ]:
C:/numpy/random/temporar/stiueuce/random.py

In [32]:
import numpy as np 

TypeError: function missing required argument 'year' (pos 1)

In [ ]:
np.random.temporar.stiueuce.random()

In [38]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponen

In [60]:
lista1 = [1,2.0,5,7.7,8, np.nan]
lista2 = [3,4,5,9,0, np.nan]
lista3 = [2,5,7,9,1, np.nan]

lista_listelor = [lista1, lista2, lista3]
lista_listelor

[[1, 2.0, 5, 7.7, 8, nan], [3, 4, 5, 9, 0, nan], [2, 5, 7, 9, 1, nan]]

In [62]:
matrice_din_liste = np.array(lista_listelor)
matrice_din_liste

array([[1. , 2. , 5. , 7.7, 8. , nan],
       [3. , 4. , 5. , 9. , 0. , nan],
       [2. , 5. , 7. , 9. , 1. , nan]])

In [53]:
type(np.nan)

float

In [54]:
matrice_din_liste[0,2]

5.0

In [55]:
type(matrice_din_liste[0,2])

numpy.float64

In [63]:
lista1 = [1,2.0,5,7.7,8]
lista2 = [3,4,5,9,0]
lista3 = [2,5,7,9,1]

lista_listelor2 = [lista1, lista2, lista3]
lista_listelor2

[[1, 2.0, 5, 7.7, 8], [3, 4, 5, 9, 0], [2, 5, 7, 9, 1]]

In [75]:
matrice_din_liste2 = np.array(lista_listelor2)
matrice_din_liste2

array([[1. , 2. , 5. , 7.7, 8. ],
       [3. , 4. , 5. , 9. , 0. ],
       [2. , 5. , 7. , 9. , 1. ]])

In [76]:
matrice3 =matrice_din_liste2.astype("int16")

In [66]:
matrice3

array([[1, 2, 5, 7, 8],
       [3, 4, 5, 9, 0],
       [2, 5, 7, 9, 1]], dtype=int16)

In [70]:
matrice3.ndim

2

In [71]:
matrice3.shape

(3, 5)

In [73]:
matrice3.reshape(5,3)

array([[1, 2, 5],
       [7, 8, 3],
       [4, 5, 9],
       [0, 2, 5],
       [7, 9, 1]], dtype=int16)

In [77]:
matrice3.T

array([[1, 3, 2],
       [2, 4, 5],
       [5, 5, 7],
       [7, 9, 9],
       [8, 0, 1]], dtype=int16)

In [78]:
conditie = np.where(matrice3 >= 7)

In [79]:
matrice3[conditie]

array([7, 8, 9, 7, 9], dtype=int16)

In [80]:
matrice3[np.where(matrice3 >= 7)]

array([7, 8, 9, 7, 9], dtype=int16)

In [81]:
type(conditie)

tuple

In [83]:
conditie

array([0, 0, 1, 2, 2])

In [84]:
#dir(matrice3)

In [85]:
matrice3

array([[1, 2, 5, 7, 8],
       [3, 4, 5, 9, 0],
       [2, 5, 7, 9, 1]], dtype=int16)

In [86]:
matrice3[1:, 2:]

array([[5, 9, 0],
       [7, 9, 1]], dtype=int16)

In [88]:
matrice3.sum()

68

In [89]:
matrice3.mean()

4.533333333333333

In [90]:
matrice3[1:, 2:].mean()

5.166666666666667

In [91]:
matrice3.cumsum()

array([ 1,  3,  8, 15, 23, 26, 30, 35, 44, 44, 46, 51, 58, 67, 68])

In [92]:
matrice3.shape

(3, 5)

In [93]:
matrice3.max()

9

In [94]:
matrice3.min()

0

In [105]:
matrice_distante_egale = np.linspace(0, 9, 5, dtype="int32")

In [106]:
matrice_distante_egale

array([0, 2, 4, 6, 9], dtype=int32)

In [107]:
lista_de_numere = [1, 23, 4, 31, 1, 1, 4, 23, 4, 1]

In [108]:
matrice4 = np.array(lista_de_numere)
matrice4

array([ 1, 23,  4, 31,  1,  1,  4, 23,  4,  1])

In [110]:
np.unique(matrice4)

array([ 1,  4, 23, 31])

In [111]:
un_set =set(lista_de_numere)

In [113]:
lista_noua = list(un_set)
lista_noua

[1, 4, 31, 23]

In [115]:
matrice3.diagonal()

array([1, 4, 7], dtype=int16)

In [116]:
matrice3

array([[1, 2, 5, 7, 8],
       [3, 4, 5, 9, 0],
       [2, 5, 7, 9, 1]], dtype=int16)

In [119]:
matrice5 = matrice3[:, :3]

In [120]:
matrice5

array([[1, 2, 5],
       [3, 4, 5],
       [2, 5, 7]], dtype=int16)

In [122]:
matrice5.diagonal().sum()

12

In [126]:
matrice5.flatten()

array([1, 2, 5, 3, 4, 5, 2, 5, 7], dtype=int16)

In [125]:
set(list(matrice5.flatten()))

{1, 2, 3, 4, 5, 7}

In [129]:
matrice6 = np.arange(2, 11).reshape(3,3)
matrice6

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
matrice7 = matrice6.reshape(3,3)

In [131]:
matrice6.size

9

In [135]:
matrice7.reshape(5,2)

ValueError: cannot reshape array of size 9 into shape (5,2)

In [136]:
matrice8 = np.arange(2, 11).reshape(3,3)
matrice8

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [139]:
matrice9 = np.arange(10,31, 4)
matrice9

array([10, 14, 18, 22, 26, 30])

In [146]:
matrice10 = np.random.randint(10,30, 6)

In [147]:
matrice10

array([16, 23, 22, 17, 19, 18])

In [148]:
matrice11 = np.random.randint(10,30, (1,6))
matrice11

array([[27, 11, 14, 14, 15, 28]])

In [149]:
matrice10.ndim, matrice11.ndim

(1, 2)

In [152]:
import pandas as pd

In [151]:
import sys
!{sys.executable} -m pip install pandas

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  Using cached pandas-1.4.3-cp39-cp39-macosx_10_9_x86_64.whl (11.5 MB)
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621


In [153]:
df = pd.DataFrame(matrice5)

In [154]:
df

0  1  2
0  1  2  5
1  3  4  5
2  2  5  7

In [155]:
type(df)

pandas.core.frame.DataFrame

In [156]:
df.shape

(3, 3)

In [166]:
df.median()

0    2.0
1    4.0
2    5.0
dtype: float64

In [158]:
df.mean()

0    2.000000
1    3.666667
2    5.666667
dtype: float64

In [159]:
df.sum()

0     6
1    11
2    17
dtype: int64

In [161]:
df.iloc[0,0]

1

In [165]:
df[2].unique()

array([5, 7], dtype=int16)

In [169]:
matrice8

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [170]:
matrice8.any()

True

In [171]:
matrice8.all()

True

In [168]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 

In [172]:
df.dtypes

0    int16
1    int16
2    int16
dtype: object

In [173]:
df[2] = df[2].astype("float16")
df

0  1    2
0  1  2  5.0
1  3  4  5.0
2  2  5  7.0

In [174]:
df.dtypes

0      int16
1      int16
2    float16
dtype: object

# Exercitiu din programa

In [180]:
matrice = np.arange(10)
matrice

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
matrice[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [182]:
matrice2 = np.array(list(reversed(matrice)))

In [183]:
matrice2

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])